package net.horus.pointage.models;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CardRfid generated by hbm2java
 */
@Entity
@Table(name="card_rfid"
    ,catalog="pointage"
    , uniqueConstraints = {@UniqueConstraint(columnNames="numero_carte"), @UniqueConstraint(columnNames="identifiant_carte")} 
)
public class CardRfid  implements java.io.Serializable {


     private Integer id;
     private Employes employes;
     private String isValide;
     private String maricule;
     private String numeroCarte;
     private String identifiantCarte;

    public CardRfid() {
    }

	
    public CardRfid(Employes employes, String isValide) {
        this.employes = employes;
        this.isValide = isValide;
    }
    public CardRfid(Employes employes, String isValide, String maricule, String numeroCarte, String identifiantCarte) {
       this.employes = employes;
       this.isValide = isValide;
       this.maricule = maricule;
       this.numeroCarte = numeroCarte;
       this.identifiantCarte = identifiantCarte;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="employe_id", nullable=false)
    public Employes getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Employes employes) {
        this.employes = employes;
    }

    
    @Column(name="is_valide", nullable=false, length=2)
    public String getIsValide() {
        return this.isValide;
    }
    
    public void setIsValide(String isValide) {
        this.isValide = isValide;
    }

    
    @Column(name="maricule", length=50)
    public String getMaricule() {
        return this.maricule;
    }
    
    public void setMaricule(String maricule) {
        this.maricule = maricule;
    }

    
    @Column(name="numero_carte", unique=true, length=50)
    public String getNumeroCarte() {
        return this.numeroCarte;
    }
    
    public void setNumeroCarte(String numeroCarte) {
        this.numeroCarte = numeroCarte;
    }

    
    @Column(name="identifiant_carte", unique=true, length=50)
    public String getIdentifiantCarte() {
        return this.identifiantCarte;
    }
    
    public void setIdentifiantCarte(String identifiantCarte) {
        this.identifiantCarte = identifiantCarte;
    }




}


