package net.horus.pointage.models;
// Generated 22 f�vr. 2020 � 01:57:26 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EmployeSortiePointage generated by hbm2java
 */
@Entity
@Table(name="employe_sortie_pointage"
    ,catalog="pointage"
)
public class EmployeSortiePointage  implements java.io.Serializable {


     private Integer id;
     private Employes employes;
     private Date jour;
     private Date heureSortie;
     private Date heureRetour;
     private String numeroCarte;
     private String marticuleEmploye;

    public EmployeSortiePointage() {
    }

    public EmployeSortiePointage(Employes employes, Date jour, Date heureSortie, Date heureRetour, String numeroCarte, String marticuleEmploye) {
       this.employes = employes;
       this.jour = jour;
       this.heureSortie = heureSortie;
       this.heureRetour = heureRetour;
       this.numeroCarte = numeroCarte;
       this.marticuleEmploye = marticuleEmploye;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="employe_id")
    public Employes getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Employes employes) {
        this.employes = employes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jour", length=10)
    public Date getJour() {
        return this.jour;
    }
    
    public void setJour(Date jour) {
        this.jour = jour;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_sortie", length=8)
    public Date getHeureSortie() {
        return this.heureSortie;
    }
    
    public void setHeureSortie(Date heureSortie) {
        this.heureSortie = heureSortie;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="heure_retour", length=8)
    public Date getHeureRetour() {
        return this.heureRetour;
    }
    
    public void setHeureRetour(Date heureRetour) {
        this.heureRetour = heureRetour;
    }

    
    @Column(name="numero_carte", length=50)
    public String getNumeroCarte() {
        return this.numeroCarte;
    }
    
    public void setNumeroCarte(String numeroCarte) {
        this.numeroCarte = numeroCarte;
    }

    
    @Column(name="marticule_employe", length=50)
    public String getMarticuleEmploye() {
        return this.marticuleEmploye;
    }
    
    public void setMarticuleEmploye(String marticuleEmploye) {
        this.marticuleEmploye = marticuleEmploye;
    }




}


