package net.horus.pointage.models;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="groupe"
    ,catalog="pointage"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Groupe  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Employes> employeses = new HashSet<Employes>(0);

    public Groupe() {
    }

	
    public Groupe(String name) {
        this.name = name;
    }
    public Groupe(String name, Set<Employes> employeses) {
       this.name = name;
       this.employeses = employeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="employe_groupe", catalog="pointage", joinColumns = { 
        @JoinColumn(name="groupe_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="employe_id", nullable=false, updatable=false) })
    public Set<Employes> getEmployeses() {
        return this.employeses;
    }
    
    public void setEmployeses(Set<Employes> employeses) {
        this.employeses = employeses;
    }




}


